version: '3.7'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'Europe/London'
    env_file:
      - '.env'
    volumes:
      - '/data/pihole/pihole/:/etc/pihole/'
      - '/data/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
