apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pi-tjth-co
  namespace: default
spec:
  secretName: pi-tjth-co
  issuerRef:
    name: letsencrypt-cloudflare
    kind: Issuer
  commonName: 'pihole.tjth.co'
  dnsNames:
  - 'pihole.tjth.co'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "pihole"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "pihole"
