apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-web-password
  namespace: pihole
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-web-password
  data:
  - secretKey: password 
    remoteRef: 
      key: pihole/credentials
      property: password