apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-web-password
  namespace: pihole
spec:
  encryptedData:
    password: AgCCCVZI9gmtN/e+vVmi9/HehJ9yVWJUqfSc2CKU0FHLvgfDCZvWm/sKqST4dFIBy4mGPZYxYjd5fkXy8rYdAmxgbw/o9EJRf2Ws5eo3M50rZ7YFbqx+pBbAXkgqDYb585u/+dx4KpWN3DE+fqZl1OFHjGYV79jZyN8g/c6b7kkqwcOIvEBporBelpELvKm9doAphyKTdGVh9OphVhXtrk+mZo3mOUVnnBwti9tSiogrpyD8XvY+2L0JqKT5nxlc/c1IdVzmtZrEg+XQPZoqt1PwC5BvFHZe74EKGkfApAWxZudyccwEI0HYt3V/Z1mhmNxuP6uClZCoQeoxA1rVdmk3zYzU8GeiMsveaYQkXayBi+FH3bCLdcapB5wuudDl/atgtpzgcNg6Gzi+LgDYScV6FfdT6i3Db1JFcbfIbzGIABNHfQ1AN8fmOKbApE/MZ7+IkMQg4f8oONvfY9c2p+cEwJbyqd4ITBohQRhdWxXnBhVuL4ZJALpoNakYfreIsaBwPEyYagyLcE+JUbLUvfJb+adLBp8aS0GnDHs6W+AP/yVyoswgittbBBfU9co6OstqKZAzkfImpB80/y6XRJXR88DeKYOIpvS9XH23aTFJ7sJasOkn9UgFhIVFuD4qnDY5MvowvpKtBHuRXXjajBQyj4+BV1mr1sWZdZ0IZAi58YMLublKtcCOSQ4sG5kj2M1PYeE20LhBtprcOCYniRk=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-web-password
      namespace: pihole
    type: Opaque

