apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-web-password
  namespace: pihole
spec:
  encryptedData:
    password: AgCBzd+WsKIU4/e1QNIlZ8yS6H2/cGJWYSEoVVtomQOoosRvSw2um//Aoqu08S2yvDcKApWBcEqQg5f/eTlbDZ0vrARMPBigAM7LuNhIN4R/gKworrzCxhnXT+O/K+78XURg7qiIm/Cgpjzr2R/nuPl8RaG/TZHz07sCi6LgF20lLHcpMAgMp/P8d28nPDSJa4g9geNstzLBTah6yrei74s0cxTsfC3wbv6i1l4RRwylnqsIPnku7tkAHcquguFPQZKoqsGtByP7eQCifQQk8DbQCuvkd9jo5zT6Oar5x/hnmvmU3PnnAutQwgYRKR6MY+C1IcSWQ6oaj48U7rvMOBwqWWiM+ZusfnZEGYtcIhbSgSB57RIYxI6RTuZtMYQxwPQkylgEfiWQoyNmsBSeBHW2LZ5McIpEzf+fwGKBzCoxdP2bOTaV+Y2gPEwnmEs8dPI/ARofofZcjQwP0EDZ3KADyzTkUhT6XgtRrCW+ah13XZeqvaNwt2TMBmpeC6UPcnc7nVjsbo/eLgLqXAri9o1N8Hjttf58bmD2+3BSUKSKn7WwRBpBCm3nDvhwfb4UfzCwsQK0H6lDWWGqsvdVpTCi8J4AHc2+y1sVVeIICRZw3XeKeUn4o5kiD44DkAmSBVQCC0WYtt6G/F+XPPV/HC97Ei+tcHDAPQsdBM5RUKj5xTC+Zj4AJtT8oBbAAoJV8cBdG0VDakcFpXWeer71SkE=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-web-password
      namespace: pihole

