---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: pihole
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - pihole
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: pihole
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          image: pihole/pihole:latest
          ports:
            - containerPort: 53
              protocol: UDP
              name: pihole-dns
            - containerPort: 53
              protocol: TCP
              name: pihole-dns-tcp
            - containerPort: 80
              protocol: TCP
              name: pihole-http
            - containerPort: 67
              protocol: UDP
              name: pihole-dhcp
          env:
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-web-password
                  key: password
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - name: pihole-etc
              mountPath: /etc/pihole/
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d/\
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-etc
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  ports:
    - port: 53
      name: pihole-dns
      protocol: UDP
      targetPort: pihole-dns
    - port: 53
      name: pihole-dns-tcp
      protocol: TCP
      targetPort: pihole-dns-tcp
    - port: 80
      name: pihole-http
      protocol: TCP
      targetPort: pihole-http
    - port: 67
      name: pihole-dhcp
      protocol: UDP
      targetPort: pihole-dhcp
  selector:
    app: pihole
