name: pihole
namespace: pihole
replicas: 1
node_affinity: False
security_context: '[ "NET_ADMIN" ]'
image: pihole/pihole:2023.05.2
ports:
  - containerPort: 53
    protocol: UDP
    name: pihole-dns
  - containerPort: 53
    protocol: TCP
    name: pihole-dns-tcp
  - containerPort: 80
    protocol: TCP
    name: pihole-http
  - containerPort: 67
    protocol: UDP
    name: pihole-dhcp
env:
  - name: TZ
    value: "Europe/London"
env_from:
  - name: WEBPASSWORD
    secret_key_name: pihole-web-password
    key: password
volume_mounts:
  - name: pihole-etc
    mountPath: /etc/pihole/
  - name: pihole-dnsmasq
    mountPath: /etc/dnsmasq.d/
volumes:
  - name: pihole-etc
    claimName: pihole-etc
  - name: pihole-dnsmasq
    claimName: pihole-dnsmasq
service_type: LoadBalancer
pvc:
  - name: pihole-etc
    storage: 1Gi
  - name: pihole-dnsmasq
    storage: 500Mi
external_traffic_policy: Local