name: Comment diff

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  argocd-diff:
    runs-on: self-hosted
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.tjth.co
          method: jwt
          role: kb
          secrets: |
                secret/data/argocd/credentials ARGOCD_USER;
                secret/data/argocd/credentials ARGOCD_PASSWORD;
                secret/data/argocd/credentials ARGOCD_SERVER;
      # Install argocd cli
      - name: Setup ArgoCD
        run: |
          # Install argocd
          mkdir -p ~/bin
          curl -sSL -o ~/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          # Make executable
          chmod +x ~/bin/argocd
          # Add bin to PATH in GITHUB_ENV
          echo "PATH=$PATH:~/bin" >> $GITHUB_ENV

      - name: Diff ArgoCD app
        id: argocd-diff
        env:
          ARGOCD_USER: ${{ steps.import-secrets.outputs.ARGOCD_USER }}
          ARGOCD_PASSWORD: ${{ steps.import-secrets.outputs.ARGOCD_PASSWORD }}
          ARGOCD_SERVER: ${{ steps.import-secrets.outputs.ARGOCD_SERVER }}
        shell: bash
        run: |
          # Login to argocd
          ~/bin/argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USER" --password "$ARGOCD_PASSWORD" --insecure --plaintext
          
          app_diff=$(~/bin/argocd app diff pihole --server "$ARGOCD_SERVER" --server-side-generate --local $(pwd) --insecure || true)
          
          echo -e "$app_diff"
          
          # Write app_diff to output
          echo "ARGOCD_APP_DIFF<<EOF"$'\n'"$app_diff"$'\n'EOF >> "$GITHUB_OUTPUT"

      - name: Update diff comment
        uses: actions/github-script@v7
        env:
          DIFF_COMMENT: ${{ steps.argocd-diff.outputs.ARGOCD_APP_DIFF }}
        with:
          script: |
            const commentBody = "## ArgoCD app diff:\n\n```" + process.env.DIFF_COMMENT + "\n```\n";

            const comments = await github.rest.issues.listComments({
              issue_number: context.payload.pull_request.number, 
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            if (comments.length === 0) {
              // No comments, create a default one
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: commentBody
              })
            } else {
              // Check existing comments
              const existingComment = comments.data.find(c => c.body.includes('ArgoCD app diff'));

              if (existingComment) {
                // Update existing comment
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existingComment.id,
                  body: commentBody
                })
              } else {
                // Create new comment
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  body: commentBody
                })
              }
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
